# Generated by Django 4.1.2 on 2022-10-27 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30, verbose_name='place')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('complement', models.CharField(max_length=30, verbose_name='complement')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('uf', models.CharField(max_length=3, verbose_name='uf')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='phonenumber')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 10, 27, 18, 17, 41, 608289), verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='brand')),
                ('model', models.CharField(max_length=20, verbose_name='model')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('year', models.IntegerField(verbose_name='year')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.query')),
            ],
        ),
    ]
