# Generated by Django 4.1.2 on 2022-10-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='phonenumber')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
        ),
    ]
